spring.application.name=buildtrack
spring.datasource.url=jdbc:mysql://localhost:3306/buildtrack
spring.datasource.username=root
spring.datasource.password=Kishore@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true